# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_auto_20190304_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='name',
            new_name='author',
        ),
        migrations.AddField(
            model_name='disco',
            name='grupo',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
